### ISSUE TITLE
Please add a changelog

### ISSUE THREAD

**Issue by yvele** [jhen0409/babel-preset-es2015-node6#8]
The package recently moved from `0.3.0` to `0.4.0` but I have no idea why/what? (in fact I have [a clue](https://github.com/jhen0409/babel-preset-es2015-node6/commits/master))

Please add a changelog and/or publish you releases (with description) to GitHub: https://github.com/jhen0409/babel-preset-es2015-node6/releases

PS: See how babel is doing https://github.com/babel/babel/releases

**Comment by jhen0409** [comment]
Thanks! I'll consider this.

Actually I'm no habits add changelog to a tiny project. Just see [commits](https://github.com/jhen0409/babel-preset-es2015-node6/commits/master) should be clear. (But I didn‘t mention of recent updates is related to #4, sorry about that)
